# Generated by Django 4.2.4 on 2023-08-21 16:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0002_thread'),
    ]

    operations = [
        migrations.AddField(
            model_name='thread',
            name='started_from',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='chat.message'),
        ),
        migrations.AlterField(
            model_name='thread',
            name='messages',
            field=models.ManyToManyField(related_name='parent', to='chat.message'),
        ),
    ]
