# Generated by Django 4.2.4 on 2023-08-22 16:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0003_thread_started_from_alter_thread_messages'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='thread',
            name='users',
        ),
        migrations.AlterField(
            model_name='thread',
            name='messages',
            field=models.ManyToManyField(related_name='parent_thread', to='chat.message'),
        ),
    ]
